inst_id: "AAPLUSDT"
sqlite_path: "data/binance_aapl_tokenized.db"
history:
  rest_url: "https://fapi.binance.com/fapi/v1/klines"
  date_start: "2026-08-01"
  date_end: "2026-08-10"
  interval: "1m"
  page_limit: 1500
  request_interval_seconds: 0.10
